//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CedulasEstatalesApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class BITACORA
    {
        public long ID_BITACORA { get; set; }
        public Nullable<long> ID_CEDULA { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<byte> TIPO_MOVIMIENTO { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
    
        public virtual CAT_MOVIMIENTO CAT_MOVIMIENTO { get; set; }
        public virtual DOC_CEDULA DOC_CEDULA { get; set; }
    }
}
