//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CedulasEstatalesApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CedulaEstatalEntities : DbContext
    {
        public CedulaEstatalEntities()
            : base("name=CedulaEstatalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BITACORA> BITACORA { get; set; }
        public virtual DbSet<CAT_ESTATUS> CAT_ESTATUS { get; set; }
        public virtual DbSet<CAT_FIRMANTE> CAT_FIRMANTE { get; set; }
        public virtual DbSet<CAT_MOVIMIENTO> CAT_MOVIMIENTO { get; set; }
        public virtual DbSet<DOC_CEDULA> DOC_CEDULA { get; set; }
        public virtual DbSet<XML> XML { get; set; }
    }
}
