//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CedulasEstatalesApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOC_CEDULA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOC_CEDULA()
        {
            this.BITACORA = new HashSet<BITACORA>();
            this.XML = new HashSet<XML>();
        }
    
        public long ID_CEDULA { get; set; }
        public string CURP { get; set; }
        public string NOMBRES { get; set; }
        public string PRIMER_APELLIDO { get; set; }
        public string SEGUNDO_APELLIDO { get; set; }
        public string INSTITUCION { get; set; }
        public int ID_CARRERA { get; set; }
        public string DESC_CARRERA { get; set; }
        public string TIPO_CEDULA { get; set; }
        public Nullable<byte> ID_ESTATUS { get; set; }
        public Nullable<System.DateTime> FECHA_CARGA { get; set; }
        public Nullable<System.DateTime> FECHA_SELLO { get; set; }
        public string CEDULA_FEDERAL { get; set; }
        public string SELLO { get; set; }
        public string HASH_QR { get; set; }
        public Nullable<byte> ID_FIRMANTE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BITACORA> BITACORA { get; set; }
        public virtual CAT_ESTATUS CAT_ESTATUS { get; set; }
        public virtual CAT_FIRMANTE CAT_FIRMANTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XML> XML { get; set; }
    }
}
