//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CedulasEstatalesApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class XML
    {
        public long ID_XML { get; set; }
        public Nullable<long> ID_CEDULA { get; set; }
        public string XML1 { get; set; }
    
        public virtual DOC_CEDULA DOC_CEDULA { get; set; }
    }
}
